-- V0.7 CI 诊断表
CREATE TABLE IF NOT EXISTS `ci_diagnostics` (
    `id`              BIGINT AUTO_INCREMENT PRIMARY KEY,
    `project_id`      BIGINT       NOT NULL,
    `scan_task_id`    BIGINT       DEFAULT NULL,
    `repository_id`   BIGINT       DEFAULT NULL,
    `provider`        VARCHAR(30)  NOT NULL DEFAULT 'GITHUB_ACTIONS',
    `workflow_name`   VARCHAR(200) DEFAULT NULL,
    `workflow_run_id` VARCHAR(100) DEFAULT NULL,
    `run_number`      INT          DEFAULT NULL,
    `branch`          VARCHAR(200) DEFAULT NULL,
    `commit_sha`      VARCHAR(40)  DEFAULT NULL,
    `commit_message`  TEXT         DEFAULT NULL,
    `status`          VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING / ANALYZING / COMPLETED / FAILED',
    `conclusion`      VARCHAR(30)  DEFAULT NULL COMMENT 'success / failure / cancelled / timed_out',
    `failure_summary` TEXT         DEFAULT NULL,
    `error_category`  VARCHAR(50)  DEFAULT NULL COMMENT 'COMPILE / TEST / DEPENDENCY / LINT / DOCKER / ENV / UNKNOWN',
    `root_cause`      TEXT         DEFAULT NULL,
    `related_files`   JSON         DEFAULT NULL,
    `fix_suggestions` JSON         DEFAULT NULL,
    `raw_log_snippet` TEXT         DEFAULT NULL,
    `diagnostic_json` JSON         DEFAULT NULL,
    `error_message`   TEXT         DEFAULT NULL,
    `created_by`      BIGINT       NOT NULL,
    `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`         TINYINT(1)   NOT NULL DEFAULT 0,
    INDEX `idx_project_id` (`project_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_error_category` (`error_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;